name: Build and Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: pedagogie-logia.centralelille.fr
          FTP_USERNAME: pedagogie-logia
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: /site/
          METHOD: sftp
          PORT: 22
          ARGS: --verbose



